["module", [["data", [], {"identifier": "type_to_id", "area": [[9, 1], [72, 1]]}], ["data", [], {"identifier": "id_to_type", "area": [[75, 1], [75, 56]]}], ["data", [], {"identifier": "class_to_id", "area": [[78, 1], [84, 1]]}], ["data", [], {"identifier": "id_to_class", "area": [[87, 1], [87, 58]]}], ["data", [], {"identifier": "id_to_operation", "area": [[90, 1], [96, 1]]}], ["data", [], {"identifier": "operation_to_id", "area": [[99, 1], [101, 1]]}], ["data", [], {"identifier": "error_to_id", "area": [[104, 1], [111, 1]]}], ["data", [], {"identifier": "id_to_error", "area": [[114, 1], [114, 58]]}]], {"identifier": "/x/p/python/fault/internet/data/dns.py", "area": [[1, 1], [113, 59]], "documented": [[1, 1], [6, 3]], "source-encoding": "utf-8"}]